name: code_hannip
description: Project for start

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_mobile_ads: 0.11.0+4

  firebase_core: ^1.10.6 #new
  cloud_firestore: ^1.0.7 #^0.11.0+1
  firebase_auth: ^3.3.4 #^0.15.3+1
  firebase_messaging: ^11.2.4 #^9.0.0 #^5.1.2
  firebase_auth_web: ^3.3.5
#  reorderables: ^0.3.2
  path: ^1.8.0 #^1.6.4
  path_provider: ^2.0.0 #^1.6.11
  provider: ^5.0.0
  shared_preferences: ^2.0.0 #^0.5.12+4
  #esys_flutter_share: ^1.0.2

  flutter_platform_widgets: ^1.1.0 #^0.32.4 #^1.9.5
  flare_flutter: ^3.0.2 # #^2.0.6
  introduction_screen: ^2.1.0 # # ^1.0.9
  transformer_page_view: ^0.1.6
  camera: ^0.5.8 #^0.9.4 #
  #firebase_ml_vision: ^0.12.0+3 #^0.9.10 #discontinued
  percent_indicator: ^3.4.0 #^2.1.5
  auto_size_text: ^2.1.0
  in_app_purchase: ^0.5.2 # #

  intl: ^0.17.0
  flip_card: ^0.5.0 #^0.4.4
  google_sign_in: ^5.0.0 #^4.5.1

  #flutter_facebook_login: 3.0.0
  #apple_sign_in: ^0.1.0
  sign_in_with_apple: ^3.3.0
  #flutter_web_auth: ^0.4.0


#  http: anyls-

  flutter_launcher_icons: ^0.8.1
  flutter_screenutil: ^1.0.1
  webview_flutter: ^0.3.19+9
  marquee: ^2.2.0
  material_color_utilities: ^0.1.4
  flutter_sidekick: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/codehannip_appicon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flare/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/icons/badge0.png
    - assets/icons/badge1.png
    - assets/icons/badge2.png
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NEXON
      fonts:
        - asset: lib/assets/fonts/NEXON-LV2-Gothic-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/NEXON-LV2-Gothic-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/NEXON-LV2-Gothic-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/NEXON-LV20Gothic.ttf
          weight: 400

    - family: YANGJIN
      fonts:
        - asset: lib/assets/fonts/YANGJIN.ttf
          weight: 400

    - family: SOURCE
      fonts:
        - asset: lib/assets/fonts/SourceCodePro.ttf
          weight: 400

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
